import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCurrentUser, can } from "@/lib/permissions";
import { TopNav, type NavLink } from "@/components/TopNav";
import type { ModuleKey } from "@/lib/modules";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MODULE_LINKS: Record<ModuleKey, NavLink> = {
  os: { href: "/os", label: "Ordens de Serviço" },
  clientes: { href: "/clientes", label: "Clientes" },
  estoque: { href: "/estoque", label: "Estoque" },
  servicos: { href: "/servicos", label: "Serviços" },
  financeiro: { href: "/financeiro", label: "Financeiro" },
  usuarios: { href: "/usuarios", label: "Usuários" },
};

const CADASTRO_MODULES: ModuleKey[] = ["clientes", "estoque", "servicos", "usuarios"];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  const links = user
    ? [
        ...(can(user, "os", "view") || can(user, "financeiro", "view")
          ? [{ href: "/dashboard", label: "Dashboard" }]
          : []),
        ...(Object.keys(MODULE_LINKS) as ModuleKey[])
          .filter((key) => !CADASTRO_MODULES.includes(key) && can(user, key, "view"))
          .map((key) => MODULE_LINKS[key]),
      ]
    : [];

  const cadastroLinks = user
    ? CADASTRO_MODULES.filter((key) => can(user, key, "view")).map((key) => MODULE_LINKS[key])
    : [];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {user && <TopNav links={links} groupedLinks={cadastroLinks} userName={user.name} />}
        {children}
      </body>
    </html>
  );
}
